# Generated by Django 4.2.5 on 2023-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='model created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='model updated at')),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=155, null=True)),
                ('tnved', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SectorClassifier',
            },
        ),
    ]
