# Generated by Django 4.2.5 on 2023-12-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='model created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='model updated at')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('area', models.FloatField()),
            ],
            options={
                'db_table': 'Cluster',
            },
        ),
    ]
